export { default as AboutMe } from './AboutMe'
export { default as Pics } from './Pics'
export { default as Resume } from './Resume'
export { default as Projs } from './Projs'
export { default as Contact } from './Contact'